version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ci-debugger
    main: ./cmd/ci-debugger
    binary: ci-debugger
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows

archives:
  - id: ci-debugger
    builds: [ci-debugger]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
